spring:
  application:
    name: DotaPartyTimeBot
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=dotaparty"
  jpa:
    show-sql: true
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
  flyway:
    locations: classpath:db.migration


telegram:
  api-url: https://api.telegram.org/
  webhook-path:
  bot-name: dota_party_time_bot
  token: 7658896624:AAFLx0prYnu8Ly6B8P38i_V90DOJKbrCKCA



